/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103xx_gpio.h"
#include "stm32f103xx_interrupts.h"

// ----------------- Reloj ---------------------
// Dirección (Datasheet, pag. 33, Figure 11)
#define RCC_BASE 0x40021000U

// Estructura de registros
// (Reference Manual (RM0008), Table 19, pags. 156-158)
typedef struct
{
	volatile uint32_t CR;
	volatile uint32_t CFGR;
	volatile uint32_t CIR;
	volatile uint32_t APB2RSTR;
	volatile uint32_t APB1RSTR;
	volatile uint32_t AHBENR;
	volatile uint32_t APB2ENR;
	volatile uint32_t APB1ENR;
	volatile uint32_t BDCR;
	volatile uint32_t CSR;
	volatile uint32_t AHBSTR;
	volatile uint32_t CFGR2;
}RCC_RegDef;

#define RCC              ((RCC_RegDef*)RCC_BASE)
#define PORTA_CLK_EN()   (RCC->APB2ENR |= (1<<2)) //Pag. 146
#define AFIO_CLK_EN()    (RCC->APB2ENR |= (1<<0)) //Pag. 113
//----------------------------------------------------------

uint8_t LED_STATE = 0;

void delay(int val);

int main(void)
{
	//---------------------- GPIO Init -------------------------
	GPIO_Handle  Led_Conf;
	Led_Conf.pgpiox              = GPIOA;          //Puerto
	Led_Conf.pinConfig.pinNumber = 6;              //Pin
	Led_Conf.pinConfig.pinMode   = MODE_OUT_10MHZ; //Modo
	Led_Conf.pinConfig.pinType   = PUSH_PULL;      //Tipo de salida
	Led_Conf.pinConfig.pull      = PULL_NONE;

	GPIO_Handle  Button_Conf;
	Button_Conf.pgpiox              = GPIOA;          //Puerto
	Button_Conf.pinConfig.pinNumber = 0;              //Pin
	Button_Conf.pinConfig.pinMode   = MODE_IN;        //Modo
	Button_Conf.pinConfig.pinType   = MODE_FLOATING;  //Entrada flotante

	PORTA_CLK_EN(); // Habilitar reloj para el Puerto A

    GPIO_Pin_Init(&Led_Conf);
    GPIO_Pin_Init(&Button_Conf);
    //---------------------------------------------------------

    //------------ Configuración de interrupción --------------
    AFIO_CLK_EN();
    EINT_Init(EXTI0,RISING_FALLING,PA_PIN);
    enable_interrupt(EXTI0_IRQNUM);
    EXTI->IMR |= 0x00001; //Un-mask EXTI0 (RM0008,Sec. 10.2.4,pag. 208)
    IRQ_Priority(EXTI0_IRQNUM,1);
    //---------------------------------------------------------

    /* Loop forever */
	for(;;)
	{
		/*if(GPIO_ReadPin(GPIOA,0)==SET)
			GPIO_WritePin(GPIOA,6,SET);
		else
			GPIO_WritePin(GPIOA,6,RESET);*/
	}
}

//En STM32CubeIDE ver archivo: /Startup/startup_stm32f102c8tx.s
void EXTI0_IRQHandler(void)
{
	if(EXTI->PR & 1<<0)
	{
		EXTI->PR |= (1<<0);
		LED_STATE = GPIO_ReadPin(GPIOA,0);
		delay(600);
		if(GPIO_ReadPin(GPIOA,0)==LED_STATE)
		{
		    GPIO_TogglePin(GPIOA,6);
		}
	}
}

void delay(int val)
{
	int i;
	for(i=0;i<val;i++){}
}

